<?php
$linkfrom =  Mage::app()->getRequest()->getParam('linkfrom');

// find the way to redirect to the homepage when someone will click "back" 

switch($linkfrom) {

// Template
case '': 
$affiliatelink = '';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
	
		/*###########
		#	Amazon	#
		###########*/
		
case 'http://www.amazon.co.uk/Maximuscle-Promax-Strawberry-Protein-Powder/dp/B000OC1U4Y/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000OC1U4Y/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000OC1U4Y&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Anabolic-180caps-STRENGTH-BODYBUILDING-SUPPLEMENT/dp/B002R6CTAO/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002R6CTAO/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002R6CTAO&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Anabolic-180caps-STRENGTH-BODYBUILDING-SUPPLEMENT/dp/B002R6CTAO/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002R6CTAO/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002R6CTAO&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Sanatogen-Complete-essential-Vitamins-Minerals/dp/B001E5CH74/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001E5CH74/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001E5CH74&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Vitabiotics-Wellman-Advanced-Vitamin-Supplement/dp/B000LNHAZY/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000LNHAZY/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000LNHAZY&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Muscle-Anabolic-Chocolate-Shake-Powder/dp/B001FFL17K/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001FFL17K/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001FFL17K&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Gaspari-Nutrition-SuperPump-Pre-Workout-Powder/dp/B0016QALBU/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0016QALBU/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0016QALBU&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Anabolic-Mass-PLUS-500mg-Development/dp/B005PQ5C2A/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B005PQ5C2A/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B005PQ5C2A&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/SMARTSHAKE-Protein-Shaker-Mutant-600/dp/B005454ZHA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B005454ZHA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B005454ZHA&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/REDFASTER-Best-Energy-Drink-Pineapple/dp/B002UJZLQC/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002UJZLQC/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002UJZLQC&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/OPTIMUM-NUTRITION-CAPS-SAME-DISPATCH/dp/B000FIA7AA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000FIA7AA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000FIA7AA&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Magnum-8000-Mass-Weight-Builder/dp/B007AAML1O/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B007AAML1O/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B007AAML1O&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/BSN-True-Mass-Vanilla-5-75lbs/dp/B004GL1TKY/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B004GL1TKY/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004GL1TKY&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/OPTIMUM-NUTRITION-MICRONIZED-CREATINE-UNFLAVOURED/dp/B004CR7PN2/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B004CR7PN2/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004CR7PN2&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Ultralean-Chocolate-Weight-Control-Replacement/dp/B0013GMDBO/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0013GMDBO/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0013GMDBO&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Recover-Tropical-Post-Workout-Recovery-Powder/dp/B003Q80JCC/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003Q80JCC/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003Q80JCC&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Hyperbolic-Mass-Strawberry-2000g-CLF-USN-MUS014/dp/B00BGAWYUC/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00BGAWYUC/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00BGAWYUC&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/ALRI-Pro-Anabol-Generation-Pro-Anabolic-Supplement/dp/B00117YKM0/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00117YKM0/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00117YKM0&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/All-American-Kre-Alkalyn-EFX-Capsules/dp/B004IAF8U0/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B004IAF8U0/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004IAF8U0&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/All-American-Kre-Alkalyn-750mg-Capsules/dp/B00117ZRXQ/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00117ZRXQ/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00117ZRXQ&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.amazon.co.uk/Anabolic-Ravenous-Appetite-Enhancer-Capsules/dp/B004LSDV0S/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B004LSDV0S/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004LSDV0S&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Forza-Glutamino-L-Glutamine-Protein-Power/dp/B00A4CFLX0/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00A4CFLX0/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00A4CFLX0&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Optimum-Nutrition-Energy-Orange-Recovery/dp/B004PYN4DM/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B004PYN4DM/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004PYN4DM&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-Sculptress-Caramel-Crunch-Protein/dp/B006L2R1MG/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B006L2R1MG/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B006L2R1MG&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-Sculptress-Diet-Chocolate-700g/dp/B005QSC2V6/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B005QSC2V6/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B005QSC2V6&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-Definity-Body-Toning-Softgels/dp/B003EEMIS6/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003EEMIS6/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003EEMIS6&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-Definity-Strawberry-Toning-Recovery/dp/B003EEMIRM/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003EEMIRM/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003EEMIRM&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-MTSCREW-Shaker-500ml/dp/B003EEMISQ/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003EEMISQ/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003EEMISQ&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maxitone-750-ml-Water-Bottle/dp/B003EEMITA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003EEMITA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003EEMITA&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Cyclone-Bars-Choc-Box/dp/B003VCXVFK/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003VCXVFK/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003VCXVFK&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Creatamax-Extreme-Orange-Strength/dp/B000TM1KY4/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0028Y4OGM/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0028Y4OGM&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Creatamax-300g-CLF-MX-CR3/dp/B00B5VZVPC/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00B5VZVPC/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00B5VZVPC&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Creatamax-120-capsule-CLF-MX-CCAP/dp/B00B5VZVHK/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002F5GVHY/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002F5GVHY&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Progain-Strawberry-3000g-CLF-MX-PGS3KG/dp/B00B5W09KS/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00B5W09KS/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00B5W09KS&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Progain-Chocolate-Strength-Powder/dp/B000OC1UIA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000OC1UIA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000OC1UIA&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Progain-Strawberry-Strength-Powder/dp/B001FFCEXU/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001FFCEXU/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001FFCEXU&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Progain-Flapjack-12x-90G/dp/B002Q106C8/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002Q106C8/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002Q106C8&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Progain-Extreme-Strawberry-Strength/dp/B000TLT4A2/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000TLT4A2/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000TLT4A2&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Maxi-Power-800g/dp/B0017TVVBA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0017TVVBA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0017TVVBA&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-HMB-1000-60ct/dp/B001M0V85I/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001M0V85I/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001M0V85I&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-ZMA-30ct/dp/B0036QP3YI/ref=sr_1_1?ie': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0036QP3YI/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0036QP3YI&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Chocolate-Protein-Powder/dp/B001FFCF0C/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001FFCF0C/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001FFCF0C&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Meal-Bar-Chocolate/dp/B009M3U6ZU/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B009M3U6ZU/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B009M3U6ZU&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Extreme-Chocolate-Protein/dp/B001FFCERQ/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B001FFCERQ/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B001FFCERQ&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Breakfast-Oats-Choc/dp/B00B5W0DKY/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00B5W0DKY/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00B5W0DKY&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Multi-Release-Raspberry/dp/B00B5W0M0U/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00B5W0M0U/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00B5W0M0U&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'www.amazon.co.uk/Maximuscle-Maxi-Milk-Chocolate-Ready--Recovery/dp/B002A9J9WO/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B002A9J9WO/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B002A9J9WO&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'www.amazon.co.uk/Maximuscle-Promax-Amino-Acid-Capsules/dp/B000TLR346/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000TLR346/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000TLR346&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Cyclone-Strawberry-Strength-Powder/dp/B000OZ71IA/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000OZ71IA/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000OZ71IA&linkCode=as2&tag=shopsupp247-';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Strawberry-Protein-Powder/dp/B000OC1U4Y/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000OC1U4Y/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000OC1U4Y&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Strawberry-Weight-Definition/dp/B000OC0EFK/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B000OC0EFK/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B000OC0EFK&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Promax-Diet-Bars-Chocolate/dp/B004IZ3MBC/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B0043VW9RO/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B0043VW9RO&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Maximuscle-Cla-1000mg-Softgels-CLF-MX-CLA90/dp/B00B5VZRDI/ref': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00B5VZRDI/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00B5VZRDI&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/Universal-Nutrition-Animal-Burner-Weight/dp/B004EMNELW/ref=': 
$affiliatelink='http://www.amazon.co.uk/gp/product/B004EMNELW/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B004EMNELW&linkCode=as2&tag=shopsupp247-21'; 		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.amazon.co.uk/dp/B003AXAG7G/': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B003AXAG7G/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B003AXAG7G&linkCode=as2&tag=shopsupp247-21';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
// 7 november	
case 'http://www.amazon.co.uk/Optimum-Nutrition-Wholly-Strawberries-Recovery/dp/B00FK8BXKS/ref=': 
$affiliatelink = 'http://www.amazon.co.uk/gp/product/B00FK8BXKS/ref=as_li_ss_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00FK8BXKS&linkCode=as2&tag=shopsupp247-21';	
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	

		/*###################################
		#	www.discount-supplements.co.uk	#	
		//#################################*/
		
case 'http://www.discount-supplements.co.uk/sports-supplements-glucosamine-joint-support-universal-animal-flex-44-packs': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-glucosamine-joint-support-universal-animal-flex-44-packs';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/usn-muscle-fuel-anabolic-4kg-tub?utm_source=#.UjGiCn8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fusn-muscle-fuel-anabolic-4kg-tub%3Futm_source%3D#.UjGiCn8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/maximuscle-maxipower-800g?utm_source=GoogleBase&utm_medium=#.UjH12H8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fmaximuscle-maxipower-800g%3Futm_source%3DGoogleBase%26utm_medium%3D#.UjH12H8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-weight-gainers-maximuscle-progain-extreme-2-1kg?utm_source=#.UjH80X8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-weight-gainers-maximuscle-progain-extreme-2-1kg%3Futm_source%3D#.UjH80X8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-creatine-maximuscle-creatamax-120-caps?utm_source=#.UjIL4X8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-creatine-maximuscle-creatamax-120-caps%3Futm_source%3D#.UjIL4X8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-creatine-maximuscle-creatamax-300g?utm_source=#.UjIST38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-creatine-maximuscle-creatamax-300g%3Futm_source%3D#.UjIST38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.discount-supplements.co.uk/sports-supplements-creatine-maximuscle-creatamax-extreme-1103g?utm_source=#.Ujc6MH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-creatine-maximuscle-creatamax-extreme-1103g%3Futm_source%3D#.Ujc6MH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-high-protein-bars-maximuscle-cyclone-bars-12-x-60g-bars?utm_source=#.Ujc7mH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-high-protein-bars-maximuscle-cyclone-bars-12-x-60g-bars%3Futm_source%3D#.Ujc7mH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-amino-acid-supplements-maximuscle-promax-amino-275-caps?utm_source=#.UjdbvH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-amino-acid-supplements-maximuscle-promax-amino-275-caps%3Futm_source%3D#.UjdbvH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-amino-acid-supplements-maximuscle-hmb-60-x-1000mg-caps?utm_source=#.UjidRH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-amino-acid-supplements-maximuscle-hmb-60-x-1000mg-caps%3Futm_source%3D#.UjidRH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-weight-gainers-maximuscle-progain-2kg?utm_source=#.Ujifn38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-weight-gainers-maximuscle-progain-2kg%3Futm_source%3D#.Ujifn38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/maximuscle-progain-3kg-tub?utm_source=#.UjinTX8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fmaximuscle-progain-3kg-tub%3Futm_source%3D#.UjinTX8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/maximuscle-maxi-milk-rtd-8-x-330ml-bottle-s?utm_source=#.UjizVH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fmaximuscle-maxi-milk-rtd-8-x-330ml-bottle-s%3Futm_source%3D#.UjizVH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-fat-loss-fat-burners-maximuscle-thermobol-30-caps?utm_source=#.UkCKan8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-fat-loss-fat-burners-maximuscle-thermobol-30-caps%3Futm_source%3D#.UkCKan8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/health-supplements-fat-loss-efa-omega-fish-oils-maximuscle-cla-1000-90-x-1000mg-softgels?utm_source=#.UkCUEX8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fhealth-supplements-fat-loss-efa-omega-fish-oils-maximuscle-cla-1000-90-x-1000mg-softgels%3Futm_source%3D#.UkCUEX8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/usn-diet-fuel-2kg-tub#.UkCZeH8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fusn-diet-fuel-2kg-tub#.UkCZeH8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-meal-replacements-mrp-maximuscle-promax-diet-1-2kg?utm_source=#.UkCdHn8fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-meal-replacements-mrp-maximuscle-promax-diet-1-2kg%3Futm_source%3D#.UkCdHn8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-high-protein-bars-maximuscle-promax-diet-bar-12-x-60g-bars?utm_source=#.UkCyQn8fi_I':$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-high-protein-bars-maximuscle-promax-diet-bar-12-x-60g-bars%3Futm_source%3D#.UkCyQn8fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-male-support-maximuscle-zma-30-caps?utm_source=#.UkC9B38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-male-support-maximuscle-zma-30-caps%3Futm_source%3D#.UkC9B38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-whey-protein-maximuscle-promax-extreme-0-91kg?utm_source=#.UkXzn38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-whey-protein-maximuscle-promax-extreme-0-91kg%3Futm_source%3D#.UkXzn38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-whey-protein-maximuscle-cyclone-1-2kg?utm_source=#.UkX6o38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-whey-protein-maximuscle-cyclone-1-2kg%3Futm_source%3D#.UkX6o38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-whey-protein-maximuscle-promax-extreme-0-91kg?utm_source=#.UksPS38fi_I': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-whey-protein-maximuscle-promax-extreme-0-91kg%3Futm_source%3D#.UksPS38fi_I';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case 'http://www.discount-supplements.co.uk/sports-supplements-protein-bars-optimum-nutrition-high-protein-oat-bar-12-x-77g-bars': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=2394&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.discount-supplements.co.uk%2Fsports-supplements-protein-bars-optimum-nutrition-high-protein-oat-bar-12-x-77g-bars';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;	
case '': 
$affiliatelink = '';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;


		/*###############
		#	maxishop	#
		###############*/
	
case 'http://www.maxishop.com/maximuscle/lean-definition/cla1000': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Flean-definition%2Fcla1000';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/lean-definition/thermobol-mini': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Flean-definition%2Fthermobol-mini';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/lean-definition/promax-diet-bars': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Flean-definition%2Fpromax-diet-bars';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/lean-definition/promax-lean': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Flean-definition%2Fpromax-lean';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/cyclone': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fcyclone';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-aminos': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-aminos';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/maxinutrition-protein-milk': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fmaxinutrition-protein-milk';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/maxi-milk': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fmaxi-milk';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/maxi-milk-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fmaxi-milk-extreme';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-multi-release': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-multi-release';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-breakfast-oats': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-breakfast-oats';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-extreme-mini-tub': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-extreme-mini-tub';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-meal-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-meal-bar';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax-mini-tub': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax-mini-tub';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/zma': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fzma';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/hmb1000': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fhmb1000';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/maxipower': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/progain-extreme': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fprogain-extreme';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/progain-flapjack': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fprogain-flapjack';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/progain-mini-tub': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fprogain-mini-tub';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fprogain';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/progain3': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fmaximuscle-creatamax-';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/maximuscle-creatamax-capsules': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fmaximuscle-creatamax-capsules';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/creatamax300': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fcreatamax300';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/creatamax-extreme': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fcreatamax-';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/size-and-strength/cyclone-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fsize-and-strength%2Fcyclone-bar';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/accessories/gymbag': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Faccessories%2Fgymbag';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/accessories/waterbottle': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Faccessories%2Fwaterbottle';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/accessories/electric-pink-water-bottle': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Faccessories%2Felectric-pink-water-';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/accessories/': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Faccessories%2Fshaker';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/body-toning/definity-protein-plus': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fbody-toning%2Fdefinity-protein-plus';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/body-toning/definitycla': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fbody-toning%2Fdefinitycla';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/weight-loss/sculptress-diet-drink': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fweight-loss%2Fsculptress-diet-drink';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/weight-loss/sculptresstablets': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fweight-loss%2Fsculptresstablets';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/weight-loss/sculptressdiet': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fweight-loss%2Fsculptressdiet';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/amino-acids/primary-glutamine-500g': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Famino-acids%2Fprimary-glutamine-500g';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/amino-acids/primaryarginine': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Famino-acids%2Fprimaryarginine';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/amino-acids/primary-hmb-250g': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Famino-acids%2Fprimary-hmb-250g';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/amino-acids/primarybeta-alanine': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Famino-acids%2Fprimarybeta-alanine';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/amino-acids/primary-bcaa': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Famino-acids%2Fprimary-bcaa';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/caseinsustain': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fcaseinsustain';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/massblitz': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fmassblitz';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/massblitz-25': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fmassblitz-25';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/protein-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fprotein-complex';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/protein-complex-50': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fprotein-complex-50';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/wpi-intensity-50': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fwpi-intensity-50';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/wpc-precision-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fwpc-precision-';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/protein/wpc-precision': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fprotein%2Fwpc-precision';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/smart-': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fsmart-shaker';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/accessories/waterbottle': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Faccessories%2Fwaterbottle';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/weight-loss/turbotherm': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fweight-loss%2Fturbotherm';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/pre-workout/turbotest': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fpre-workout%2Fturbotest';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/pre-workout/': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fpre-workout%2Fcaffeine';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxiraw/creatine/creatine-charge-500g': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxiraw%2Fcreatine%2Fcreatine-charge-500g';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maxitone/weight-loss/sculptressdietbar': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaxitone%2Fweight-loss%2Fsculptressdietbar';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://www.maxishop.com/maximuscle/high-protein/promax?gclid=CNTA0IG67LkCFUjA3godbwwAOQ': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=1495&awinaffid=188069&clickref=&p=http%3A%2F%2Fwww.maxishop.com%2Fmaximuscle%2Fhigh-protein%2Fpromax%3Fgclid%3DCNTA0IG67LkCFUjA3godbwwAOQ';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;				

		/*###################################
		#	http://monstersupplements.com	#	
		//#################################*/


case 'http://monstersupplements.com/store/p/4283/1/Optimum-Nutrition-Platinum-Hydro-Whey-795g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4283%2F1%2FOptimum-Nutrition-Platinum-Hydro-Whey-795g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/4282/1/Optimum-Nutrition-Platinum-Hydro-Whey-1588g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4282%2F1%2FOptimum-Nutrition-Platinum-Hydro-Whey-1588g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5846/1/Optimum-Nutrition-Platinum-PRE--300g-plus-2-ON-sample-sachets.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5846%2F1%2FOptimum-Nutrition-Platinum-PRE--300g-plus-2-ON-sample-sachets.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/442/1/Optimum-Nutrition-Pro-Complex---1kg.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F442%2F1%2FOptimum-Nutrition-Pro-Complex---1kg.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5890/1/Optimum-Nutrition-Pro-Complex-2.09Kg.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5890%2F1%2FOptimum-Nutrition-Pro-Complex-2.09Kg.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/443/1/Optimum-Nutrition-Serious-Mass---12lb--5.4-Kg-and-FREE-ON-Sample-Sachet.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F443%2F1%2FOptimum-Nutrition-Serious-Mass---12lb--5.4-Kg-and-FREE-ON-Sample-Sachet.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/444/1/Optimum-Nutrition-Tribulus---100-caps.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F444%2F1%2FOptimum-Nutrition-Tribulus---100-caps.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/4593/1/Optimum-Nutrition-Opti-Men.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4593%2F1%2FOptimum-Nutrition-Opti-Men.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5528/1/Optimum-Nutrition-Opti-Men.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5528%2F1%2FOptimum-Nutrition-Opti-Men.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5248/1/Optimum-Nutrition-Opti-Women-60-caps.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5248%2F1%2FOptimum-Nutrition-Opti-Women-60-caps.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3683/1/Optimum-Nutrition-Nitro-Core-24-1364g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3683%2F1%2FOptimum-Nutrition-Nitro-Core-24-1364g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/4817/1/Optimum-Nutrition-Micronized-Creatine-300g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4817%2F1%2FOptimum-Nutrition-Micronized-Creatine-300g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5896/1/Optimum-Nutrition-Lean-Whey-930g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5896%2F1%2FOptimum-Nutrition-Lean-Whey-930g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5895/1/Optimum-Nutrition-Lean-Whey-465g-.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5895%2F1%2FOptimum-Nutrition-Lean-Whey-465g-.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5195/1/Optimum-Nutrition-Hydro-Builder-1Kg-.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5195%2F1%2FOptimum-Nutrition-Hydro-Builder-1Kg-.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3658/1/Optimum-Nutrition-Glyco-Maize-2-Kg.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3658%2F1%2FOptimum-Nutrition-Glyco-Maize-2-Kg.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3363/1/Optimum-Nutrition-2:1:1-Recovery-3.73lb.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3363%2F1%2FOptimum-Nutrition-2%3A1%3A1-Recovery-3.73lb.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3366/1/Optimum-Nutrition-Amino-2222-Soft-gels-300.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3366%2F1%2FOptimum-Nutrition-Amino-2222-Soft-gels-300.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5266/1/Optimum-Nutrition-Amino-Energy-30-servings.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5266%2F1%2FOptimum-Nutrition-Amino-Energy-30-servings.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/447/1/Optimum-Nutrition-100-WHEY-PROTEIN-5lb.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F447%2F1%2FOptimum-Nutrition-100-WHEY-PROTEIN-5lb.html=';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/445/1/Optimum-Nutrition-100-WHEY-PROTEIN-10lb.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F445%2F1%2FOptimum-Nutrition-100-WHEY-PROTEIN-10lb.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/446/1/Optimum-Nutrition-100-WHEY-PROTEIN---2lb.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F446%2F1%2FOptimum-Nutrition-100-WHEY-PROTEIN---2lb.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3964/1/Optimum-Nutrition-100-natural-Oats-and-whey-.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3964%2F1%2FOptimum-Nutrition-100-natural-Oats-and-whey-.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3682/1/Optimum-Nutrition-100-Gold-Standard-Casein.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3682%2F1%2FOptimum-Nutrition-100-Gold-Standard-Casein.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/4886/1/Optimum-Nutrition-100-Gold-Standard-Casein-1.8kg.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4886%2F1%2FOptimum-Nutrition-100-Gold-Standard-Casein-1.8kg.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3963/1/Optimum-Nutrition-100-Egg-protein.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3963%2F1%2FOptimum-Nutrition-100-Egg-protein.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/5496/1/Optimum-Nutrition---Enteric-Coated-Fish-Oils-200-softgels.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F5496%2F1%2FOptimum-Nutrition---Enteric-Coated-Fish-Oils-200-softgels.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/4603/1/Optimum-Nutrition-Wholly-Oats-Bars-X-12.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F4603%2F1%2FOptimum-Nutrition-Wholly-Oats-Bars-X-12.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/367/1/Maximuscle-Cyclone-:-1.2kg.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F367%2F1%2FMaximuscle-Cyclone-%3A-1.2kg.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/344/1/Maximuscle-Promax---2lb.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F344%2F1%2FMaximuscle-Promax---2lb.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3778/1/Maximuscle-Promax-Mini-454G.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3778%2F1%2FMaximuscle-Promax-Mini-454G.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/3692/1/Maximuscle-Progain-Flapjack-12x-90G.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F3692%2F1%2FMaximuscle-Progain-Flapjack-12x-90G.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/407/1/Maximuscle-Promax-Diet-Bar---12-bars.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F407%2F1%2FMaximuscle-Promax-Diet-Bar---12-bars.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/389/1/Maximuscle-Promax-Meal-Bar---12-bars.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F389%2F1%2FMaximuscle-Promax-Meal-Bar---12-bars.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/363/1/Maximuscle-CLA-1000---90-softgels.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F389%2F1%2FMaximuscle-Promax-Meal-Bar---12-bars.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/383/1/Maximuscle---HMB-1000---60-caps.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F383%2F1%2FMaximuscle---HMB-1000---60-caps.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/696/1/Maximuscle-Creatamax-300---300g.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F696%2F1%2FMaximuscle-Creatamax-300---300g.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/697/1/Maximuscle-Creatamax-Caps---120-Caps.html': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F697%2F1%2FMaximuscle-Creatamax-Caps---120-Caps.html';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;
case 'http://monstersupplements.com/store/p/2717/1/Universal-Animal-Flex-44-paks.html#.UbRHzvltgpA': 
$affiliatelink = 'http://www.awin1.com/cread.php?awinmid=3596&awinaffid=188069&clickref=&p=http%3A%2F%2Fmonstersupplements.com%2Fstore%2Fp%2F2717%2F1%2FUniversal-Animal-Flex-44-paks.html%23.UbRHzvltgpA';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;


		/*###########################
		#	www.mutantnutrition.com	#	
		//#########################*/


case 'http://www.mutantnutrition.com/animal-flex-44ct.html': 
$affiliatelink = 'http://www.mutantnutrition.com/animal-flex-44ct.html?acc=d3d9446802a44259755d38e6d163e820';		
header( 'refresh: 3; url=' . $affiliatelink  );	      
break;







				
	
	
default:

header( 'refresh: 3; url=' . $linkfrom  );
}
?>
<div style="text-align:center; margin-top:20px; font-family:Arial, Helvetica, sans-serif;">

 

  <h1>Thanks for visiting Shop Supplements 24/7</h1><br>
  <p>We hope you have found what you were looking for!</p>
 <img src="http://www.shopsupplements247.com/skin/frontend/default/modern/images/loading_icon.gif" id="loading" />
  <p>We are now redirecting you to your chosen product</p>
  
  <br />
  <br />
<span style="font-style:italic; font-size:10px; color: #999;">If page doesn't load,<a href="http://www.yourteamarket.com/contactus/">click here</a> to let us know.</span> 
</div>